// Code generated by gobind. DO NOT EDIT.

// Java class trojan.Trojan is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/trojan-gfw/igniter-go-libs/trojan
package trojan;

import go.Seq;

public abstract class Trojan {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Trojan() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native void runClient(String filename);
	/**
	 * SetLoglevel set trojan log level
	possible input: debug/info/warn/error/none
	 */
	public static native void setLoglevel(String logLevel);
	public static native void stopClient();
}
