// Code generated by gobind. DO NOT EDIT.

// Java class version.Version is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java TrojanCat/version
package version;

import go.Seq;

public abstract class Version {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Version() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	public static native String version();
}
